packages:
  - "apps/*"
  - "packages/*"
  - "services/*"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true

enableGlobalVirtualStore: true

catalog:
  '@effect/platform-bun': 4.0.0-rc.113
  effect: 4.0.0-rc.113
  typescript: ^7.0.2
