// @ts-nocheck
// Auto-generated by scripts/gen-migrations.ts — do not edit manually

import m0000 from '../drizzle/0000_luxuriant_sasquatch.sql' with {
  type: 'text',
};
import m0001 from '../drizzle/0001_mute_inertia.sql' with { type: 'text' };
import journal from '../drizzle/meta/_journal.json' with { type: 'json' };

export default {
  journal: journal as {
    entries: { idx: number; when: number; tag: string; breakpoints: boolean }[];
  },
  files: {
    '0000_luxuriant_sasquatch': m0000,
    '0001_mute_inertia': m0001,
  } as Record<string, string>,
};
